[package]
name = "concurrency_testing"
version = "0.1.0"
edition = "2021"
authors = ["Anton Velikanov <a.velikanov.jobs@gmail.com>"]

[dependencies]
loom = "0.7.1"

[target.'cfg(loom)'.dependencies]
loom = "0.7.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }
